/***********************************************************************************************************************            
#OBJETIVO............: PROCEDURE RESPOSAVEL PELOS SERVICOS DE LOGIN 
#CRIADO POR..........: 31/03/2023 - CARLOS EDUARDO R. DA SILVA            
#REVISADO POR........:     
#ALTERADO POR........:    
#ALTERAÇÃO...........:    
#PERMISSÃO...........:     
***********************************************************************************************************************/          
CREATE PROCEDURE PR_SR_LOGIN (  
	@ID_SERVICO INT,  
	@ID_PESSOA INT = NULL,
	@NOME VARCHAR(50) = NULL,
	@ID_TIPO_PESSOA INT = NULL,
	@EMAIL VARCHAR(255) = NULL,
	@SENHA VARCHAR(255) = NULL,
	@RA VARCHAR(6) = NULL,
	@USUARIO VARCHAR(50) = NULL,
	@IMG VARCHAR(MAX) = NULL
)AS          
BEGIN          
  --  DESCRIÇÃO @ID_SERVICO
		--1 - LOGAR
		--2 - CADASTRAR USUARIO
		--3 - EDITAR USUARIO
		--4 - APAGAR USER
		--5 - BUSCAR USER

	--LOGAR
	IF @ID_SERVICO = 1 
	BEGIN
		SELECT ID_PESSOA FROM TB_PESSOA WHERE EMAIL = @EMAIL AND SENHA = @SENHA AND FL_ATIVO = 1
	END

	--CADASTRAR USUARIO
	ELSE IF @ID_SERVICO = 2 
	BEGIN
		INSERT INTO TB_PESSOA VALUES (@NOME, @ID_TIPO_PESSOA, @EMAIL, @SENHA, @RA, @USUARIO, @IMG, GETDATE(), 1)
		SELECT ID_PESSOA FROM TB_PESSOA WHERE EMAIL = @EMAIL AND SENHA = @SENHA AND FL_ATIVO = 1
	END

	--EDITAR USUARIO
	ELSE IF @ID_SERVICO = 3 
	BEGIN
		UPDATE TB_PESSOA SET NOME = @NOME, ID_TIPO_PESSOA = @ID_TIPO_PESSOA, EMAIL = @EMAIL, SENHA = @SENHA, RA = @RA, USUARIO = @USUARIO, IMG = @IMG WHERE ID_PESSOA = @ID_PESSOA
		SELECT ID_PESSOA FROM TB_PESSOA WHERE EMAIL = @EMAIL AND SENHA = @SENHA AND FL_ATIVO = 1
	END

	--APAGAR USER
	ELSE IF @ID_SERVICO = 4
	BEGIN
		UPDATE TB_PESSOA SET FL_ATIVO = 0 WHERE ID_PESSOA = @ID_PESSOA
	END

	--BUSCAR USER
	ELSE IF @ID_SERVICO = 5
	BEGIN
		SELECT 
			ID_SERVICO,  
			ID_PESSOA,
			NOME,
			ID_TIPO_PESSOA,
			EMAIL,
			SENHA,
			RA,
			USUARIO,
			IMG
		WHERE ID_PESSOA = @ID_PESSOA
	END
END